### PR TITLE
add `useWaitForTransaction` support & export all types & fix useProvider bug

### PR DESCRIPTION
**Pull request by loktarjugg**
`useProvider` use the klona to deep clone will be triggering an error `Maximum call stack size exceeded error`
i replace the klona with markRaw to fix it

@wobsoriano

### CODE REVIEW

**Comment by murongg** [comment]
LGTM

**Comment by wobsoriano** [comment]
lgtm

**Comment by wobsoriano** [comment]
BTW if you try to build vagmi you'll get

```bash
src/composables/providers/useProvider.ts(11,17): error TS4058: Return type of exported function has or is using name 'RawSymbol' from external module "/Users/Desktop/tmp/vagmi/node_modules/.pnpm/@vue+reactivity@3.2.37/node_modules/@vue/reactivity/dist/reactivity" but cannot be named.
```

**Comment by loktarjugg** [comment]
> lgtm. I think we can safely remove `klona` in deps
I also think it's possible to remove it

**Comment by loktarjugg** [comment]
> BTW if you try to build vagmi you'll get
> 
> ```shell
> src/composables/providers/useProvider.ts(11,17): error TS4058: Return type of exported function has or is using name 'RawSymbol' from external module "/Users/Desktop/tmp/vagmi/node_modules/.pnpm/@vue+reactivity@3.2.37/node_modules/@vue/reactivity/dist/reactivity" but cannot be named.
> ```

This seems to be caused by ts not being able to infer markRaw wrapped in ref, i will fix it later

**Pull request merged**
